/**
 * Field Model (Sequelize/MySQL)
 * Stores field boundary information and metadata
 */

const { DataTypes } = require("sequelize");
const { sequelize } = require("../config/database");
const crypto = require("crypto");

/**
 * Generate unique field ID
 * Format: FIELD-YYYYMMDD-XXXXXX (e.g., FIELD-20251029-A3B5C7)
 */
// function generateFieldId() {
//   const date = new Date();
//   const dateStr = date.toISOString().split("T")[0].replace(/-/g, "");
//   const randomStr = crypto.randomBytes(3).toString("hex").toUpperCase();
//   return `FIELD-${dateStr}-${randomStr}`;
// }


const Field = sequelize.define(
  "Field",
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
    },
    field_id: {
      type: DataTypes.STRING(100),
      allowNull: true, // Allow null during creation, will be auto-generated by hook
      unique: true,
      comment: "Auto-generated unique field identifier",
    },
    user_id: {
      type: DataTypes.STRING(100),
      allowNull: true,
      comment: "Owner user ID",
    },
    boundary_type: {
      type: DataTypes.STRING(50),
      defaultValue: "Polygon",
      comment: "GeoJSON type",
    },
    boundary_coordinates: {
      type: DataTypes.TEXT("long"),
      allowNull: false,
      comment: "GeoJSON coordinates as JSON string",
    },
    name: {
      type: DataTypes.STRING(255),
      comment: "Field name",
    },
    crop_type: {
      type: DataTypes.STRING(100),
      comment: "Current crop type",
    },
    planting_date: {
      type: DataTypes.DATE,
      comment: "Planting date",
    },
    harvest_date: {
      type: DataTypes.DATE,
      comment: "Expected harvest date",
    },
    farm_name: {
      type: DataTypes.STRING(255),
      comment: "Farm name",
    },
    location: {
      type: DataTypes.STRING(255),
      comment: "Location description",
    },
    notes: {
      type: DataTypes.TEXT,
      comment: "Additional notes",
    },
    tags: {
      type: DataTypes.TEXT,
      comment: "Tags as JSON array",
    },
    area_sqm: {
      type: DataTypes.DECIMAL(15, 2),
      allowNull: false,
      comment: "Area in square meters",
    },
    area_hectares: {
      type: DataTypes.DECIMAL(15, 4),
      allowNull: false,
      comment: "Area in hectares",
    },
    perimeter_m: {
      type: DataTypes.DECIMAL(15, 2),
      comment: "Perimeter in meters",
    },
    status: {
      type: DataTypes.ENUM("active", "inactive", "archived"),
      defaultValue: "active",
      comment: "Field status",
    },
  },
  {
    tableName: "fields",
    indexes: [
      { fields: ["field_id"] },
      { fields: ["user_id"] },
      { fields: ["crop_type"] },
      { fields: ["status"] },
    ],
    hooks: {
      // beforeValidate: async (field) => {
      //   // Auto-generate field_id if not provided or null
      //   if (!field.field_id || field.field_id === null) {
      //     let isUnique = false;
      //     let attempts = 0;
      //     const maxAttempts = 10;

      //     while (!isUnique && attempts < maxAttempts) {
      //       field.field_id = generateFieldId();

      //       // Check if this ID already exists
      //       const existing = await Field.findOne({
      //         where: { field_id: field.field_id },
      //       });

      //       if (!existing) {
      //         isUnique = true;
      //       }
      //       attempts++;
      //     }

      //     if (!isUnique) {
      //       throw new Error(
      //         "Failed to generate unique field_id after multiple attempts"
      //       );
      //     }

      //     console.log(`🆔 Auto-generated field_id: ${field.field_id}`);
      //   }
      // },
    },
  }
);

// Instance methods
Field.prototype.toJSON = function () {
  const values = Object.assign({}, this.get());
  // Parse boundary coordinates
  if (values.boundary_coordinates) {
    try {
      values.boundary = {
        type: values.boundary_type,
        coordinates: JSON.parse(values.boundary_coordinates),
      };
      delete values.boundary_type;
      delete values.boundary_coordinates;
    } catch (e) {
      // Keep as is if parsing fails
    }
  }
  // Parse tags
  if (values.tags) {
    try {
      values.tags = JSON.parse(values.tags);
    } catch (e) {
      values.tags = [];
    }
  }
  // Add virtual field
  values.area_acres = parseFloat(values.area_hectares) * 2.47105;
  return values;
};

// Static methods
/**
 * Create a new field with auto-generated field_id
 */
Field.createField = async function (fieldData) {
  const {
    fieldBoundary,
    user_id,
    name,
    crop_type,
    planting_date,
    harvest_date,
    farm_name,
    location,
    notes,
    tags,
    field_id
  } = fieldData;

  // Validate required fields
  if (!fieldBoundary || !fieldBoundary.coordinates) {
    throw new Error("Field boundary is required");
  }

  // Calculate area (simplified - using bounding box)
  const coords = fieldBoundary.coordinates[0];
  let minLat = coords[0][1],
    maxLat = coords[0][1];
  let minLon = coords[0][0],
    maxLon = coords[0][0];

  coords.forEach((coord) => {
    minLat = Math.min(minLat, coord[1]);
    maxLat = Math.max(maxLat, coord[1]);
    minLon = Math.min(minLon, coord[0]);
    maxLon = Math.max(maxLon, coord[0]);
  });

  // Approximate area calculation (in square meters)
  const latDiff = (maxLat - minLat) * 111320; // 1 degree latitude ≈ 111.32 km
  const lonDiff =
    (maxLon - minLon) * 111320 * Math.cos((minLat * Math.PI) / 180);
  const area_sqm = Math.abs(latDiff * lonDiff);
  const area_hectares = area_sqm / 10000;

  // Create field (field_id will be auto-generated by beforeCreate hook)
  const field = await Field.create({
    user_id,
    boundary_type: fieldBoundary.type || "Polygon",
    boundary_coordinates: JSON.stringify(fieldBoundary.coordinates),
    name,
    crop_type,
    planting_date,
    harvest_date,
    farm_name,
    location,
    notes,
    tags: tags ? JSON.stringify(tags) : null,
    area_sqm,
    area_hectares,
    field_id,
    status: "active",
  });

  console.log(`✅ Created new field with auto-generated ID: ${field.field_id}`);
  return field;
};

module.exports = Field;
